### PR TITLE
As an admin, I can change the roles of other existing users - Glory / Toyin

### PR DESCRIPTION
**Pull request by glozy**
- Added view for changing of user roles
- Added functionalities to be able to change a user's role to admin
- Added Edit User nav-bar only visible to an admin
- Added unit tests

### CODE REVIEW

**Review by jurczakn — CHANGES_REQUESTED** [review]
add tests to the nav-bar spec for the new link created

**Comment by glozy** [comment]
Noted

**Comment by glozy** [comment]
added jasmine test for the edit role link in the nav-bar

**Review by jurczakn — APPROVED** [review]
Ok, test added

**Pull request merged**
